-- AlterTable: Add new feature fields to Property
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasParkingSpace" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasCellar" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasTerrace" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasPool" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasAirConditioning" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "isFurnished" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasConcierge" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "hasAlarm" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable: Add cost/detail fields to Property
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "condominiumFees" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "extraCosts" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "condition" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "heatingType" TEXT;

-- AlterTable: Add billing fields to Agency
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "ragioneSociale" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "partitaIva" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "codiceFiscale" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "pec" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "codiceSdi" TEXT DEFAULT '0000000';
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "invoiceAddress" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "invoiceCity" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "invoiceProvince" TEXT;
ALTER TABLE "Agency" ADD COLUMN IF NOT EXISTS "invoiceCap" TEXT;
